# Generated by Django 3.0.3 on 2020-03-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_file_name', models.CharField(max_length=50)),
                ('weight_file', models.FileField(upload_to='')),
            ],
        ),
    ]
