# Generated by Django 3.0.3 on 2020-03-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightfile',
            name='weight_file',
            field=models.FileField(upload_to='weight_upload'),
        ),
    ]
