# Generated by Django 3.0.3 on 2020-03-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200312_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file_name', models.CharField(max_length=50)),
                ('model_file', models.FileField(upload_to='model_upload/')),
            ],
        ),
    ]
