# Generated by Django 3.0.3 on 2020-03-13 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_modelfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfile',
            name='model_file_name',
        ),
        migrations.RemoveField(
            model_name='weightfile',
            name='weight_file_name',
        ),
        migrations.AddField(
            model_name='modelfile',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weightfile',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
