# Generated by Django 3.0.3 on 2020-03-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200313_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='weightfile',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
