# Generated by Django 3.0.3 on 2020-03-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200313_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='session_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weightfile',
            name='session_expired',
            field=models.BooleanField(default=False),
        ),
    ]
