# Generated by Django 3.0.3 on 2020-03-13 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200313_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weightfile',
            name='id',
        ),
        migrations.AddField(
            model_name='modelfile',
            name='model_file_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for model file.', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='weightfile',
            name='weight_file_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for weight file.', primary_key=True, serialize=False),
        ),
    ]
