# Generated by Django 3.0.3 on 2020-03-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200314_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelfile',
            old_name='model_file_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='weightfile',
            old_name='weight_file_id',
            new_name='id',
        ),
    ]
