# Generated by Django 3.0.3 on 2020-03-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200314_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfile',
            name='session_expired',
        ),
        migrations.RemoveField(
            model_name='weightfile',
            name='session_expired',
        ),
    ]
